console.log('number' + 3 + 3, 'number33 — конкатенація');
console.log(null + 3, '3 — приведення null до 0');
console.log(5 && "qwerty", '"qwerty" — повернення останньої складової виразу');
console.log(+'40' + +'2' + "hillel", '42hillel — приведення 40 та 2 до числа, складання їх та конкатенація');
console.log('10' - 5 === 6, 'false — приводення \'10\' до числа, віднімання(10-5), поріаняння 5 === 6');
console.log(true + false, '1 — приведення true до 1, false до 0 та складання');
console.log('4px' - 3, 'NaN — \'4px\' до числа = NaN, операції з NaN дорівнюють NaN');
console.log('4' - 3, '1 — \'4\' до числа = 4');
console.log('6' + 3 ** 0, '61 — возведення у степень та конкатенація');
console.log(12 / '6', '2 — приведення 6 до числа');
console.log('10' + (5 === 6), '10false — порівняння та конкатенація');
console.log(null == '', 'false — null дорівнює тіки null або undefined');
console.log(3 ** (9 / 3), '27 — спочатку операції у дужках');
console.log(!!'false' == !!'true', 'true — не порожні строки це true');
console.log(0 || '0' && 1, '1 — спочатку && потім ||, && поверне 1, || поверне 1 бо 0 це false');
console.log((+null == false) < 1, 'false — +null це 0, 0 == false буде true, true == false буде false');
console.log(false && true || true, 'true — спочатку && що дасть false, потім || до поверне перший позитивний вираз');
console.log(false && (false || true), 'false — бо && поверне перший негативний результат');
console.log((+null == false) < 1 ** 5, 'false — спочатку +null, потім порівнянн, возведіння у ступінь та порівняннь true < 1 що є false бо true це 1');